### Health Check

GET http://localhost:4000/health HTTP/1.1

### Create a new user

POST http://localhost:4000/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john@doe.com",
  "password": "securepassword"
}

### Login with existing user

POST http://localhost:4000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "john@doe.com",
  "password": "securepassword"
}

### Create a new task

POST http://localhost:4000/api/task/create HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc2MDg1MzU3OSwiZXhwIjoxNzYwODU3MTc5fQ.nCBt9HHM0YWS_3ZNoPJ6KZyuZRR02u4XnUakT7mrhbs
Content-Type: application/json

{
  "title": "Finish the project",
  "description": "Complete the express task manager app by end of the week."
}

### Update a task
PUT http://localhost:4000/api/task/update/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc2MDg1ODU2OSwiZXhwIjoxNzYwODYyMTY5fQ.l71y-khVFB3qi-02-3nqtpLSYNXqkCVoSxZrH72Pjyw
Content-Type: application/json

{
  "title": "Finish the report",
  "description": "Complete the report by end of the week."
}