services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task_manager_db
    ports:
      - "33061:3306"
    volumes:
      - db_data:/var/lib/mysql8

volumes:
  db_data:
